services:
  - type: web
    name: pdf-converter
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
